"""Generic control-only prerequisites for the draft M38 protocol.

These utilities are synthetic/component-level infrastructure.  Importing this package does
not access spectra, RV products, timestamps, or target-specific artifacts.
"""

from exosat_rv.m38.convergence import (
    ConvergenceDataError,
    ConvergencePolicy,
    ConvergenceResult,
    ConvergenceUpdate,
    RVChangeMetric,
    TemplateChangeMetric,
    evaluate_convergence,
    rv_change_metric,
    template_change_metric,
)
from exosat_rv.m38.firewall import (
    FileAccess,
    FirewallViolation,
    InformationFirewall,
    enforce_output_fields,
)
from exosat_rv.m38.period_search import (
    AdaptivePipelineCalibration,
    PeriodSearchResult,
    PipelineOutcome,
    PipelineTrial,
    calibrate_global_max_statistic,
    run_adaptive_pipeline_calibration,
    weighted_sinusoid_search,
)
from exosat_rv.m38.provenance import (
    ImmutableFileRecord,
    ManifestVerificationError,
    append_stage_manifest,
    build_stage_manifest,
    verify_manifest_chain,
)
from exosat_rv.m38.selection import (
    ArmAssessment,
    ArmGates,
    ArmRosterEntry,
    AttritionPolicy,
    EquivalenceInterval,
    HiddenValidationResult,
    InjectedResponse,
    InjectionPlan,
    InjectionScore,
    RecoverySlopeEstimate,
    ReferenceResponse,
    SelectionContract,
    WinnerSelection,
    apply_hidden_validation,
    assess_arm,
    estimate_recovery_slope,
    rank_eligible_arms,
    score_injection_responses,
    select_winner,
)
from exosat_rv.m38.spectral import (
    C_M_S,
    DecomposedSpectralExposure,
    InjectionDiagnostics,
    InjectionInvariance,
    SpectralInjectionResult,
    check_injection_invariants,
    convolve_fixed_lsf,
    inject_stellar_velocity,
    relativistic_doppler_factor,
    shift_stellar_component,
)

__all__ = [
    "C_M_S",
    "AdaptivePipelineCalibration",
    "ArmAssessment",
    "ArmGates",
    "ArmRosterEntry",
    "AttritionPolicy",
    "ConvergenceDataError",
    "ConvergencePolicy",
    "ConvergenceResult",
    "ConvergenceUpdate",
    "DecomposedSpectralExposure",
    "EquivalenceInterval",
    "FileAccess",
    "FirewallViolation",
    "HiddenValidationResult",
    "ImmutableFileRecord",
    "InformationFirewall",
    "InjectedResponse",
    "InjectionDiagnostics",
    "InjectionInvariance",
    "InjectionPlan",
    "InjectionScore",
    "ManifestVerificationError",
    "PeriodSearchResult",
    "PipelineOutcome",
    "PipelineTrial",
    "RVChangeMetric",
    "RecoverySlopeEstimate",
    "ReferenceResponse",
    "SelectionContract",
    "SpectralInjectionResult",
    "TemplateChangeMetric",
    "WinnerSelection",
    "append_stage_manifest",
    "apply_hidden_validation",
    "assess_arm",
    "build_stage_manifest",
    "calibrate_global_max_statistic",
    "check_injection_invariants",
    "convolve_fixed_lsf",
    "enforce_output_fields",
    "estimate_recovery_slope",
    "evaluate_convergence",
    "inject_stellar_velocity",
    "rank_eligible_arms",
    "relativistic_doppler_factor",
    "run_adaptive_pipeline_calibration",
    "rv_change_metric",
    "score_injection_responses",
    "select_winner",
    "shift_stellar_component",
    "template_change_metric",
    "verify_manifest_chain",
    "weighted_sinusoid_search",
]
